### ISSUE TITLE
migrate package publishing to sonatype

### ISSUE THREAD

**Issue by erikerlandson** [erikerlandson/snowball#2]

**Comment by erikerlandson** [comment]
depends on https://github.com/erikerlandson/gibbous/issues/10

**Comment by bounim** [comment]
Sorry, it was a  duplicate of #2, closing it now. Please let me know if you need any help.

**Comment by erikerlandson** [comment]
@bounim if you want to submit a PR that replicates what I did with `gibbous`, I will be happy to test it and merge it!  Otherwise, I will give it higher priority (I wasn't sure if anyone actually used it), but might not be able to get to it for a couple weeks.

**Comment by erikerlandson** [comment]
resolved by #4
